export const GET_API_STORE = "GET_API_STORE";
export const GET_API_INFO_STORE = "GET_API_INFO_STORE";
export const GET_API_UPDATE_STORE = "GET_API_UPDATE_STORE";
export const GET_API_ADD_STORE = "GET_API_ADD_STORE";

export const RECEIVE_DATA_STORE = "RECEIVE_DATA_STORE";
