export const DEFAULT_ACTION = "DEFAULT_ACTION";
export const LOAD_MENU_REQUESTING = "LOAD_MENU_REQUESTING";
export const LOAD_MENU_SUCCESS = "LOAD_MENU_SUCCESS";
export const LOAD_MENU_ERROR = "LOAD_MENU_ERROR";
